name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: windows/amd64
          push: true
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_MP: ${{ secrets.DOCKER_MP }}
